-- =============================================================================
-- BLVBooker — Seed booker_sources comprehensively
-- =============================================================================
-- Run AFTER booker-schema.sql AND booker-verticals-expand.sql.
-- Idempotent — uses ON CONFLICT (url) DO NOTHING. Re-running is safe.
-- =============================================================================

-- Add unique constraint on url so we can upsert idempotently (safe if rerun).
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'booker_sources_url_uniq'
  ) THEN
    ALTER TABLE booker_sources ADD CONSTRAINT booker_sources_url_uniq UNIQUE (url);
  END IF;
END $$;

INSERT INTO booker_sources (vertical, source_type, label, url, city, region, active, notes) VALUES
('any', 'craigslist', 'Craigslist New York — Event gigs', 'https://newyork.craigslist.org/d/event-gigs/search/evg', 'New York', 'NY', true, NULL),
('any', 'craigslist', 'Craigslist New York — Talent gigs', 'https://newyork.craigslist.org/d/talent-gigs/search/tlg', 'New York', 'NY', true, NULL),
('visual_artist', 'craigslist', 'Craigslist New York — Creative gigs', 'https://newyork.craigslist.org/d/creative-gigs/search/crg', 'New York', 'NY', true, NULL),
('poet', 'craigslist', 'Craigslist New York — Writing gigs', 'https://newyork.craigslist.org/d/writing-gigs/search/wrg', 'New York', 'NY', true, NULL),
('any', 'craigslist', 'Craigslist Los Angeles — Event gigs', 'https://losangeles.craigslist.org/d/event-gigs/search/evg', 'Los Angeles', 'CA', true, NULL),
('any', 'craigslist', 'Craigslist Los Angeles — Talent gigs', 'https://losangeles.craigslist.org/d/talent-gigs/search/tlg', 'Los Angeles', 'CA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Los Angeles — Creative gigs', 'https://losangeles.craigslist.org/d/creative-gigs/search/crg', 'Los Angeles', 'CA', true, NULL),
('poet', 'craigslist', 'Craigslist Los Angeles — Writing gigs', 'https://losangeles.craigslist.org/d/writing-gigs/search/wrg', 'Los Angeles', 'CA', true, NULL),
('any', 'craigslist', 'Craigslist Chicago — Event gigs', 'https://chicago.craigslist.org/d/event-gigs/search/evg', 'Chicago', 'IL', true, NULL),
('any', 'craigslist', 'Craigslist Chicago — Talent gigs', 'https://chicago.craigslist.org/d/talent-gigs/search/tlg', 'Chicago', 'IL', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Chicago — Creative gigs', 'https://chicago.craigslist.org/d/creative-gigs/search/crg', 'Chicago', 'IL', true, NULL),
('poet', 'craigslist', 'Craigslist Chicago — Writing gigs', 'https://chicago.craigslist.org/d/writing-gigs/search/wrg', 'Chicago', 'IL', true, NULL),
('any', 'craigslist', 'Craigslist Dallas — Event gigs', 'https://dallas.craigslist.org/d/event-gigs/search/evg', 'Dallas', 'TX', true, NULL),
('any', 'craigslist', 'Craigslist Dallas — Talent gigs', 'https://dallas.craigslist.org/d/talent-gigs/search/tlg', 'Dallas', 'TX', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Dallas — Creative gigs', 'https://dallas.craigslist.org/d/creative-gigs/search/crg', 'Dallas', 'TX', true, NULL),
('poet', 'craigslist', 'Craigslist Dallas — Writing gigs', 'https://dallas.craigslist.org/d/writing-gigs/search/wrg', 'Dallas', 'TX', true, NULL),
('any', 'craigslist', 'Craigslist Houston — Event gigs', 'https://houston.craigslist.org/d/event-gigs/search/evg', 'Houston', 'TX', true, NULL),
('any', 'craigslist', 'Craigslist Houston — Talent gigs', 'https://houston.craigslist.org/d/talent-gigs/search/tlg', 'Houston', 'TX', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Houston — Creative gigs', 'https://houston.craigslist.org/d/creative-gigs/search/crg', 'Houston', 'TX', true, NULL),
('poet', 'craigslist', 'Craigslist Houston — Writing gigs', 'https://houston.craigslist.org/d/writing-gigs/search/wrg', 'Houston', 'TX', true, NULL),
('any', 'craigslist', 'Craigslist Washington — Event gigs', 'https://washingtondc.craigslist.org/d/event-gigs/search/evg', 'Washington', 'DC', true, NULL),
('any', 'craigslist', 'Craigslist Washington — Talent gigs', 'https://washingtondc.craigslist.org/d/talent-gigs/search/tlg', 'Washington', 'DC', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Washington — Creative gigs', 'https://washingtondc.craigslist.org/d/creative-gigs/search/crg', 'Washington', 'DC', true, NULL),
('poet', 'craigslist', 'Craigslist Washington — Writing gigs', 'https://washingtondc.craigslist.org/d/writing-gigs/search/wrg', 'Washington', 'DC', true, NULL),
('any', 'craigslist', 'Craigslist Miami — Event gigs', 'https://miami.craigslist.org/d/event-gigs/search/evg', 'Miami', 'FL', true, NULL),
('any', 'craigslist', 'Craigslist Miami — Talent gigs', 'https://miami.craigslist.org/d/talent-gigs/search/tlg', 'Miami', 'FL', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Miami — Creative gigs', 'https://miami.craigslist.org/d/creative-gigs/search/crg', 'Miami', 'FL', true, NULL),
('poet', 'craigslist', 'Craigslist Miami — Writing gigs', 'https://miami.craigslist.org/d/writing-gigs/search/wrg', 'Miami', 'FL', true, NULL),
('any', 'craigslist', 'Craigslist Philadelphia — Event gigs', 'https://philadelphia.craigslist.org/d/event-gigs/search/evg', 'Philadelphia', 'PA', true, NULL),
('any', 'craigslist', 'Craigslist Philadelphia — Talent gigs', 'https://philadelphia.craigslist.org/d/talent-gigs/search/tlg', 'Philadelphia', 'PA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Philadelphia — Creative gigs', 'https://philadelphia.craigslist.org/d/creative-gigs/search/crg', 'Philadelphia', 'PA', true, NULL),
('poet', 'craigslist', 'Craigslist Philadelphia — Writing gigs', 'https://philadelphia.craigslist.org/d/writing-gigs/search/wrg', 'Philadelphia', 'PA', true, NULL),
('any', 'craigslist', 'Craigslist Atlanta — Event gigs', 'https://atlanta.craigslist.org/d/event-gigs/search/evg', 'Atlanta', 'GA', true, NULL),
('any', 'craigslist', 'Craigslist Atlanta — Talent gigs', 'https://atlanta.craigslist.org/d/talent-gigs/search/tlg', 'Atlanta', 'GA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Atlanta — Creative gigs', 'https://atlanta.craigslist.org/d/creative-gigs/search/crg', 'Atlanta', 'GA', true, NULL),
('poet', 'craigslist', 'Craigslist Atlanta — Writing gigs', 'https://atlanta.craigslist.org/d/writing-gigs/search/wrg', 'Atlanta', 'GA', true, NULL),
('any', 'craigslist', 'Craigslist Boston — Event gigs', 'https://boston.craigslist.org/d/event-gigs/search/evg', 'Boston', 'MA', true, NULL),
('any', 'craigslist', 'Craigslist Boston — Talent gigs', 'https://boston.craigslist.org/d/talent-gigs/search/tlg', 'Boston', 'MA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Boston — Creative gigs', 'https://boston.craigslist.org/d/creative-gigs/search/crg', 'Boston', 'MA', true, NULL),
('poet', 'craigslist', 'Craigslist Boston — Writing gigs', 'https://boston.craigslist.org/d/writing-gigs/search/wrg', 'Boston', 'MA', true, NULL),
('any', 'craigslist', 'Craigslist San Francisco — Event gigs', 'https://sfbay.craigslist.org/d/event-gigs/search/evg', 'San Francisco', 'CA', true, NULL),
('any', 'craigslist', 'Craigslist San Francisco — Talent gigs', 'https://sfbay.craigslist.org/d/talent-gigs/search/tlg', 'San Francisco', 'CA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist San Francisco — Creative gigs', 'https://sfbay.craigslist.org/d/creative-gigs/search/crg', 'San Francisco', 'CA', true, NULL),
('poet', 'craigslist', 'Craigslist San Francisco — Writing gigs', 'https://sfbay.craigslist.org/d/writing-gigs/search/wrg', 'San Francisco', 'CA', true, NULL),
('any', 'craigslist', 'Craigslist Phoenix — Event gigs', 'https://phoenix.craigslist.org/d/event-gigs/search/evg', 'Phoenix', 'AZ', true, NULL),
('any', 'craigslist', 'Craigslist Phoenix — Talent gigs', 'https://phoenix.craigslist.org/d/talent-gigs/search/tlg', 'Phoenix', 'AZ', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Phoenix — Creative gigs', 'https://phoenix.craigslist.org/d/creative-gigs/search/crg', 'Phoenix', 'AZ', true, NULL),
('poet', 'craigslist', 'Craigslist Phoenix — Writing gigs', 'https://phoenix.craigslist.org/d/writing-gigs/search/wrg', 'Phoenix', 'AZ', true, NULL),
('any', 'craigslist', 'Craigslist Detroit — Event gigs', 'https://detroit.craigslist.org/d/event-gigs/search/evg', 'Detroit', 'MI', true, NULL),
('any', 'craigslist', 'Craigslist Detroit — Talent gigs', 'https://detroit.craigslist.org/d/talent-gigs/search/tlg', 'Detroit', 'MI', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Detroit — Creative gigs', 'https://detroit.craigslist.org/d/creative-gigs/search/crg', 'Detroit', 'MI', true, NULL),
('poet', 'craigslist', 'Craigslist Detroit — Writing gigs', 'https://detroit.craigslist.org/d/writing-gigs/search/wrg', 'Detroit', 'MI', true, NULL),
('any', 'craigslist', 'Craigslist Seattle — Event gigs', 'https://seattle.craigslist.org/d/event-gigs/search/evg', 'Seattle', 'WA', true, NULL),
('any', 'craigslist', 'Craigslist Seattle — Talent gigs', 'https://seattle.craigslist.org/d/talent-gigs/search/tlg', 'Seattle', 'WA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Seattle — Creative gigs', 'https://seattle.craigslist.org/d/creative-gigs/search/crg', 'Seattle', 'WA', true, NULL),
('poet', 'craigslist', 'Craigslist Seattle — Writing gigs', 'https://seattle.craigslist.org/d/writing-gigs/search/wrg', 'Seattle', 'WA', true, NULL),
('any', 'craigslist', 'Craigslist Minneapolis — Event gigs', 'https://minneapolis.craigslist.org/d/event-gigs/search/evg', 'Minneapolis', 'MN', true, NULL),
('any', 'craigslist', 'Craigslist Minneapolis — Talent gigs', 'https://minneapolis.craigslist.org/d/talent-gigs/search/tlg', 'Minneapolis', 'MN', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Minneapolis — Creative gigs', 'https://minneapolis.craigslist.org/d/creative-gigs/search/crg', 'Minneapolis', 'MN', true, NULL),
('poet', 'craigslist', 'Craigslist Minneapolis — Writing gigs', 'https://minneapolis.craigslist.org/d/writing-gigs/search/wrg', 'Minneapolis', 'MN', true, NULL),
('any', 'craigslist', 'Craigslist San Diego — Event gigs', 'https://sandiego.craigslist.org/d/event-gigs/search/evg', 'San Diego', 'CA', true, NULL),
('any', 'craigslist', 'Craigslist San Diego — Talent gigs', 'https://sandiego.craigslist.org/d/talent-gigs/search/tlg', 'San Diego', 'CA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist San Diego — Creative gigs', 'https://sandiego.craigslist.org/d/creative-gigs/search/crg', 'San Diego', 'CA', true, NULL),
('poet', 'craigslist', 'Craigslist San Diego — Writing gigs', 'https://sandiego.craigslist.org/d/writing-gigs/search/wrg', 'San Diego', 'CA', true, NULL),
('any', 'craigslist', 'Craigslist Tampa — Event gigs', 'https://tampa.craigslist.org/d/event-gigs/search/evg', 'Tampa', 'FL', true, NULL),
('any', 'craigslist', 'Craigslist Tampa — Talent gigs', 'https://tampa.craigslist.org/d/talent-gigs/search/tlg', 'Tampa', 'FL', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Tampa — Creative gigs', 'https://tampa.craigslist.org/d/creative-gigs/search/crg', 'Tampa', 'FL', true, NULL),
('poet', 'craigslist', 'Craigslist Tampa — Writing gigs', 'https://tampa.craigslist.org/d/writing-gigs/search/wrg', 'Tampa', 'FL', true, NULL),
('any', 'craigslist', 'Craigslist Denver — Event gigs', 'https://denver.craigslist.org/d/event-gigs/search/evg', 'Denver', 'CO', true, NULL),
('any', 'craigslist', 'Craigslist Denver — Talent gigs', 'https://denver.craigslist.org/d/talent-gigs/search/tlg', 'Denver', 'CO', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Denver — Creative gigs', 'https://denver.craigslist.org/d/creative-gigs/search/crg', 'Denver', 'CO', true, NULL),
('poet', 'craigslist', 'Craigslist Denver — Writing gigs', 'https://denver.craigslist.org/d/writing-gigs/search/wrg', 'Denver', 'CO', true, NULL),
('any', 'craigslist', 'Craigslist Baltimore — Event gigs', 'https://baltimore.craigslist.org/d/event-gigs/search/evg', 'Baltimore', 'MD', true, NULL),
('any', 'craigslist', 'Craigslist Baltimore — Talent gigs', 'https://baltimore.craigslist.org/d/talent-gigs/search/tlg', 'Baltimore', 'MD', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Baltimore — Creative gigs', 'https://baltimore.craigslist.org/d/creative-gigs/search/crg', 'Baltimore', 'MD', true, NULL),
('poet', 'craigslist', 'Craigslist Baltimore — Writing gigs', 'https://baltimore.craigslist.org/d/writing-gigs/search/wrg', 'Baltimore', 'MD', true, NULL),
('any', 'craigslist', 'Craigslist St. Louis — Event gigs', 'https://stlouis.craigslist.org/d/event-gigs/search/evg', 'St. Louis', 'MO', true, NULL),
('any', 'craigslist', 'Craigslist St. Louis — Talent gigs', 'https://stlouis.craigslist.org/d/talent-gigs/search/tlg', 'St. Louis', 'MO', true, NULL),
('visual_artist', 'craigslist', 'Craigslist St. Louis — Creative gigs', 'https://stlouis.craigslist.org/d/creative-gigs/search/crg', 'St. Louis', 'MO', true, NULL),
('poet', 'craigslist', 'Craigslist St. Louis — Writing gigs', 'https://stlouis.craigslist.org/d/writing-gigs/search/wrg', 'St. Louis', 'MO', true, NULL),
('any', 'craigslist', 'Craigslist Orlando — Event gigs', 'https://orlando.craigslist.org/d/event-gigs/search/evg', 'Orlando', 'FL', true, NULL),
('any', 'craigslist', 'Craigslist Orlando — Talent gigs', 'https://orlando.craigslist.org/d/talent-gigs/search/tlg', 'Orlando', 'FL', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Orlando — Creative gigs', 'https://orlando.craigslist.org/d/creative-gigs/search/crg', 'Orlando', 'FL', true, NULL),
('poet', 'craigslist', 'Craigslist Orlando — Writing gigs', 'https://orlando.craigslist.org/d/writing-gigs/search/wrg', 'Orlando', 'FL', true, NULL),
('any', 'craigslist', 'Craigslist Portland — Event gigs', 'https://portland.craigslist.org/d/event-gigs/search/evg', 'Portland', 'OR', true, NULL),
('any', 'craigslist', 'Craigslist Portland — Talent gigs', 'https://portland.craigslist.org/d/talent-gigs/search/tlg', 'Portland', 'OR', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Portland — Creative gigs', 'https://portland.craigslist.org/d/creative-gigs/search/crg', 'Portland', 'OR', true, NULL),
('poet', 'craigslist', 'Craigslist Portland — Writing gigs', 'https://portland.craigslist.org/d/writing-gigs/search/wrg', 'Portland', 'OR', true, NULL),
('any', 'craigslist', 'Craigslist Charlotte — Event gigs', 'https://charlotte.craigslist.org/d/event-gigs/search/evg', 'Charlotte', 'NC', true, NULL),
('any', 'craigslist', 'Craigslist Charlotte — Talent gigs', 'https://charlotte.craigslist.org/d/talent-gigs/search/tlg', 'Charlotte', 'NC', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Charlotte — Creative gigs', 'https://charlotte.craigslist.org/d/creative-gigs/search/crg', 'Charlotte', 'NC', true, NULL),
('poet', 'craigslist', 'Craigslist Charlotte — Writing gigs', 'https://charlotte.craigslist.org/d/writing-gigs/search/wrg', 'Charlotte', 'NC', true, NULL),
('any', 'craigslist', 'Craigslist San Antonio — Event gigs', 'https://sanantonio.craigslist.org/d/event-gigs/search/evg', 'San Antonio', 'TX', true, NULL),
('any', 'craigslist', 'Craigslist San Antonio — Talent gigs', 'https://sanantonio.craigslist.org/d/talent-gigs/search/tlg', 'San Antonio', 'TX', true, NULL),
('visual_artist', 'craigslist', 'Craigslist San Antonio — Creative gigs', 'https://sanantonio.craigslist.org/d/creative-gigs/search/crg', 'San Antonio', 'TX', true, NULL),
('poet', 'craigslist', 'Craigslist San Antonio — Writing gigs', 'https://sanantonio.craigslist.org/d/writing-gigs/search/wrg', 'San Antonio', 'TX', true, NULL),
('any', 'craigslist', 'Craigslist Austin — Event gigs', 'https://austin.craigslist.org/d/event-gigs/search/evg', 'Austin', 'TX', true, NULL),
('any', 'craigslist', 'Craigslist Austin — Talent gigs', 'https://austin.craigslist.org/d/talent-gigs/search/tlg', 'Austin', 'TX', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Austin — Creative gigs', 'https://austin.craigslist.org/d/creative-gigs/search/crg', 'Austin', 'TX', true, NULL),
('poet', 'craigslist', 'Craigslist Austin — Writing gigs', 'https://austin.craigslist.org/d/writing-gigs/search/wrg', 'Austin', 'TX', true, NULL),
('any', 'craigslist', 'Craigslist Sacramento — Event gigs', 'https://sacramento.craigslist.org/d/event-gigs/search/evg', 'Sacramento', 'CA', true, NULL),
('any', 'craigslist', 'Craigslist Sacramento — Talent gigs', 'https://sacramento.craigslist.org/d/talent-gigs/search/tlg', 'Sacramento', 'CA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Sacramento — Creative gigs', 'https://sacramento.craigslist.org/d/creative-gigs/search/crg', 'Sacramento', 'CA', true, NULL),
('poet', 'craigslist', 'Craigslist Sacramento — Writing gigs', 'https://sacramento.craigslist.org/d/writing-gigs/search/wrg', 'Sacramento', 'CA', true, NULL),
('any', 'craigslist', 'Craigslist Pittsburgh — Event gigs', 'https://pittsburgh.craigslist.org/d/event-gigs/search/evg', 'Pittsburgh', 'PA', true, NULL),
('any', 'craigslist', 'Craigslist Pittsburgh — Talent gigs', 'https://pittsburgh.craigslist.org/d/talent-gigs/search/tlg', 'Pittsburgh', 'PA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Pittsburgh — Creative gigs', 'https://pittsburgh.craigslist.org/d/creative-gigs/search/crg', 'Pittsburgh', 'PA', true, NULL),
('poet', 'craigslist', 'Craigslist Pittsburgh — Writing gigs', 'https://pittsburgh.craigslist.org/d/writing-gigs/search/wrg', 'Pittsburgh', 'PA', true, NULL),
('any', 'craigslist', 'Craigslist Cincinnati — Event gigs', 'https://cincinnati.craigslist.org/d/event-gigs/search/evg', 'Cincinnati', 'OH', true, NULL),
('any', 'craigslist', 'Craigslist Cincinnati — Talent gigs', 'https://cincinnati.craigslist.org/d/talent-gigs/search/tlg', 'Cincinnati', 'OH', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Cincinnati — Creative gigs', 'https://cincinnati.craigslist.org/d/creative-gigs/search/crg', 'Cincinnati', 'OH', true, NULL),
('poet', 'craigslist', 'Craigslist Cincinnati — Writing gigs', 'https://cincinnati.craigslist.org/d/writing-gigs/search/wrg', 'Cincinnati', 'OH', true, NULL),
('any', 'craigslist', 'Craigslist Las Vegas — Event gigs', 'https://lasvegas.craigslist.org/d/event-gigs/search/evg', 'Las Vegas', 'NV', true, NULL),
('any', 'craigslist', 'Craigslist Las Vegas — Talent gigs', 'https://lasvegas.craigslist.org/d/talent-gigs/search/tlg', 'Las Vegas', 'NV', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Las Vegas — Creative gigs', 'https://lasvegas.craigslist.org/d/creative-gigs/search/crg', 'Las Vegas', 'NV', true, NULL),
('poet', 'craigslist', 'Craigslist Las Vegas — Writing gigs', 'https://lasvegas.craigslist.org/d/writing-gigs/search/wrg', 'Las Vegas', 'NV', true, NULL),
('any', 'craigslist', 'Craigslist Kansas City — Event gigs', 'https://kansascity.craigslist.org/d/event-gigs/search/evg', 'Kansas City', 'MO', true, NULL),
('any', 'craigslist', 'Craigslist Kansas City — Talent gigs', 'https://kansascity.craigslist.org/d/talent-gigs/search/tlg', 'Kansas City', 'MO', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Kansas City — Creative gigs', 'https://kansascity.craigslist.org/d/creative-gigs/search/crg', 'Kansas City', 'MO', true, NULL),
('poet', 'craigslist', 'Craigslist Kansas City — Writing gigs', 'https://kansascity.craigslist.org/d/writing-gigs/search/wrg', 'Kansas City', 'MO', true, NULL),
('any', 'craigslist', 'Craigslist Cleveland — Event gigs', 'https://cleveland.craigslist.org/d/event-gigs/search/evg', 'Cleveland', 'OH', true, NULL),
('any', 'craigslist', 'Craigslist Cleveland — Talent gigs', 'https://cleveland.craigslist.org/d/talent-gigs/search/tlg', 'Cleveland', 'OH', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Cleveland — Creative gigs', 'https://cleveland.craigslist.org/d/creative-gigs/search/crg', 'Cleveland', 'OH', true, NULL),
('poet', 'craigslist', 'Craigslist Cleveland — Writing gigs', 'https://cleveland.craigslist.org/d/writing-gigs/search/wrg', 'Cleveland', 'OH', true, NULL),
('any', 'craigslist', 'Craigslist Columbus — Event gigs', 'https://columbus.craigslist.org/d/event-gigs/search/evg', 'Columbus', 'OH', true, NULL),
('any', 'craigslist', 'Craigslist Columbus — Talent gigs', 'https://columbus.craigslist.org/d/talent-gigs/search/tlg', 'Columbus', 'OH', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Columbus — Creative gigs', 'https://columbus.craigslist.org/d/creative-gigs/search/crg', 'Columbus', 'OH', true, NULL),
('poet', 'craigslist', 'Craigslist Columbus — Writing gigs', 'https://columbus.craigslist.org/d/writing-gigs/search/wrg', 'Columbus', 'OH', true, NULL),
('any', 'craigslist', 'Craigslist Indianapolis — Event gigs', 'https://indianapolis.craigslist.org/d/event-gigs/search/evg', 'Indianapolis', 'IN', true, NULL),
('any', 'craigslist', 'Craigslist Indianapolis — Talent gigs', 'https://indianapolis.craigslist.org/d/talent-gigs/search/tlg', 'Indianapolis', 'IN', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Indianapolis — Creative gigs', 'https://indianapolis.craigslist.org/d/creative-gigs/search/crg', 'Indianapolis', 'IN', true, NULL),
('poet', 'craigslist', 'Craigslist Indianapolis — Writing gigs', 'https://indianapolis.craigslist.org/d/writing-gigs/search/wrg', 'Indianapolis', 'IN', true, NULL),
('any', 'craigslist', 'Craigslist Nashville — Event gigs', 'https://nashville.craigslist.org/d/event-gigs/search/evg', 'Nashville', 'TN', true, NULL),
('any', 'craigslist', 'Craigslist Nashville — Talent gigs', 'https://nashville.craigslist.org/d/talent-gigs/search/tlg', 'Nashville', 'TN', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Nashville — Creative gigs', 'https://nashville.craigslist.org/d/creative-gigs/search/crg', 'Nashville', 'TN', true, NULL),
('poet', 'craigslist', 'Craigslist Nashville — Writing gigs', 'https://nashville.craigslist.org/d/writing-gigs/search/wrg', 'Nashville', 'TN', true, NULL),
('any', 'craigslist', 'Craigslist Milwaukee — Event gigs', 'https://milwaukee.craigslist.org/d/event-gigs/search/evg', 'Milwaukee', 'WI', true, NULL),
('any', 'craigslist', 'Craigslist Milwaukee — Talent gigs', 'https://milwaukee.craigslist.org/d/talent-gigs/search/tlg', 'Milwaukee', 'WI', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Milwaukee — Creative gigs', 'https://milwaukee.craigslist.org/d/creative-gigs/search/crg', 'Milwaukee', 'WI', true, NULL),
('poet', 'craigslist', 'Craigslist Milwaukee — Writing gigs', 'https://milwaukee.craigslist.org/d/writing-gigs/search/wrg', 'Milwaukee', 'WI', true, NULL),
('any', 'craigslist', 'Craigslist Raleigh — Event gigs', 'https://raleigh.craigslist.org/d/event-gigs/search/evg', 'Raleigh', 'NC', true, NULL),
('any', 'craigslist', 'Craigslist Raleigh — Talent gigs', 'https://raleigh.craigslist.org/d/talent-gigs/search/tlg', 'Raleigh', 'NC', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Raleigh — Creative gigs', 'https://raleigh.craigslist.org/d/creative-gigs/search/crg', 'Raleigh', 'NC', true, NULL),
('poet', 'craigslist', 'Craigslist Raleigh — Writing gigs', 'https://raleigh.craigslist.org/d/writing-gigs/search/wrg', 'Raleigh', 'NC', true, NULL),
('any', 'craigslist', 'Craigslist New Orleans — Event gigs', 'https://neworleans.craigslist.org/d/event-gigs/search/evg', 'New Orleans', 'LA', true, NULL),
('any', 'craigslist', 'Craigslist New Orleans — Talent gigs', 'https://neworleans.craigslist.org/d/talent-gigs/search/tlg', 'New Orleans', 'LA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist New Orleans — Creative gigs', 'https://neworleans.craigslist.org/d/creative-gigs/search/crg', 'New Orleans', 'LA', true, NULL),
('poet', 'craigslist', 'Craigslist New Orleans — Writing gigs', 'https://neworleans.craigslist.org/d/writing-gigs/search/wrg', 'New Orleans', 'LA', true, NULL),
('any', 'craigslist', 'Craigslist Memphis — Event gigs', 'https://memphis.craigslist.org/d/event-gigs/search/evg', 'Memphis', 'TN', true, NULL),
('any', 'craigslist', 'Craigslist Memphis — Talent gigs', 'https://memphis.craigslist.org/d/talent-gigs/search/tlg', 'Memphis', 'TN', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Memphis — Creative gigs', 'https://memphis.craigslist.org/d/creative-gigs/search/crg', 'Memphis', 'TN', true, NULL),
('poet', 'craigslist', 'Craigslist Memphis — Writing gigs', 'https://memphis.craigslist.org/d/writing-gigs/search/wrg', 'Memphis', 'TN', true, NULL),
('any', 'craigslist', 'Craigslist Louisville — Event gigs', 'https://louisville.craigslist.org/d/event-gigs/search/evg', 'Louisville', 'KY', true, NULL),
('any', 'craigslist', 'Craigslist Louisville — Talent gigs', 'https://louisville.craigslist.org/d/talent-gigs/search/tlg', 'Louisville', 'KY', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Louisville — Creative gigs', 'https://louisville.craigslist.org/d/creative-gigs/search/crg', 'Louisville', 'KY', true, NULL),
('poet', 'craigslist', 'Craigslist Louisville — Writing gigs', 'https://louisville.craigslist.org/d/writing-gigs/search/wrg', 'Louisville', 'KY', true, NULL),
('any', 'craigslist', 'Craigslist Richmond — Event gigs', 'https://richmond.craigslist.org/d/event-gigs/search/evg', 'Richmond', 'VA', true, NULL),
('any', 'craigslist', 'Craigslist Richmond — Talent gigs', 'https://richmond.craigslist.org/d/talent-gigs/search/tlg', 'Richmond', 'VA', true, NULL),
('visual_artist', 'craigslist', 'Craigslist Richmond — Creative gigs', 'https://richmond.craigslist.org/d/creative-gigs/search/crg', 'Richmond', 'VA', true, NULL),
('poet', 'craigslist', 'Craigslist Richmond — Writing gigs', 'https://richmond.craigslist.org/d/writing-gigs/search/wrg', 'Richmond', 'VA', true, NULL),
('musician', 'other', 'Indeed New York — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=New%20York%2C%20NY', 'New York', 'NY', true, 'Indeed job board search'),
('dj', 'other', 'Indeed New York — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=New%20York%2C%20NY', 'New York', 'NY', true, 'Indeed job board search'),
('band', 'other', 'Indeed New York — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=New%20York%2C%20NY', 'New York', 'NY', true, 'Indeed job board search'),
('singer', 'other', 'Indeed New York — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=New%20York%2C%20NY', 'New York', 'NY', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed New York — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=New%20York%2C%20NY', 'New York', 'NY', true, 'Indeed job board search'),
('any', 'other', 'Indeed New York — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=New%20York%2C%20NY', 'New York', 'NY', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Los Angeles — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Los%20Angeles%2C%20CA', 'Los Angeles', 'CA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Los Angeles — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Los%20Angeles%2C%20CA', 'Los Angeles', 'CA', true, 'Indeed job board search'),
('band', 'other', 'Indeed Los Angeles — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Los%20Angeles%2C%20CA', 'Los Angeles', 'CA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Los Angeles — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Los%20Angeles%2C%20CA', 'Los Angeles', 'CA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Los Angeles — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Los%20Angeles%2C%20CA', 'Los Angeles', 'CA', true, 'Indeed job board search'),
('any', 'other', 'Indeed Los Angeles — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Los%20Angeles%2C%20CA', 'Los Angeles', 'CA', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Chicago — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Chicago%2C%20IL', 'Chicago', 'IL', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Chicago — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Chicago%2C%20IL', 'Chicago', 'IL', true, 'Indeed job board search'),
('band', 'other', 'Indeed Chicago — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Chicago%2C%20IL', 'Chicago', 'IL', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Chicago — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Chicago%2C%20IL', 'Chicago', 'IL', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Chicago — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Chicago%2C%20IL', 'Chicago', 'IL', true, 'Indeed job board search'),
('any', 'other', 'Indeed Chicago — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Chicago%2C%20IL', 'Chicago', 'IL', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Dallas — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Dallas%2C%20TX', 'Dallas', 'TX', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Dallas — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Dallas%2C%20TX', 'Dallas', 'TX', true, 'Indeed job board search'),
('band', 'other', 'Indeed Dallas — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Dallas%2C%20TX', 'Dallas', 'TX', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Dallas — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Dallas%2C%20TX', 'Dallas', 'TX', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Dallas — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Dallas%2C%20TX', 'Dallas', 'TX', true, 'Indeed job board search'),
('any', 'other', 'Indeed Dallas — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Dallas%2C%20TX', 'Dallas', 'TX', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Houston — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Houston%2C%20TX', 'Houston', 'TX', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Houston — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Houston%2C%20TX', 'Houston', 'TX', true, 'Indeed job board search'),
('band', 'other', 'Indeed Houston — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Houston%2C%20TX', 'Houston', 'TX', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Houston — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Houston%2C%20TX', 'Houston', 'TX', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Houston — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Houston%2C%20TX', 'Houston', 'TX', true, 'Indeed job board search'),
('any', 'other', 'Indeed Houston — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Houston%2C%20TX', 'Houston', 'TX', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Washington — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Washington%2C%20DC', 'Washington', 'DC', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Washington — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Washington%2C%20DC', 'Washington', 'DC', true, 'Indeed job board search'),
('band', 'other', 'Indeed Washington — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Washington%2C%20DC', 'Washington', 'DC', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Washington — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Washington%2C%20DC', 'Washington', 'DC', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Washington — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Washington%2C%20DC', 'Washington', 'DC', true, 'Indeed job board search'),
('any', 'other', 'Indeed Washington — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Washington%2C%20DC', 'Washington', 'DC', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Miami — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Miami%2C%20FL', 'Miami', 'FL', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Miami — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Miami%2C%20FL', 'Miami', 'FL', true, 'Indeed job board search'),
('band', 'other', 'Indeed Miami — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Miami%2C%20FL', 'Miami', 'FL', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Miami — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Miami%2C%20FL', 'Miami', 'FL', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Miami — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Miami%2C%20FL', 'Miami', 'FL', true, 'Indeed job board search'),
('any', 'other', 'Indeed Miami — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Miami%2C%20FL', 'Miami', 'FL', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Philadelphia — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Philadelphia%2C%20PA', 'Philadelphia', 'PA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Philadelphia — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Philadelphia%2C%20PA', 'Philadelphia', 'PA', true, 'Indeed job board search'),
('band', 'other', 'Indeed Philadelphia — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Philadelphia%2C%20PA', 'Philadelphia', 'PA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Philadelphia — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Philadelphia%2C%20PA', 'Philadelphia', 'PA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Philadelphia — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Philadelphia%2C%20PA', 'Philadelphia', 'PA', true, 'Indeed job board search'),
('any', 'other', 'Indeed Philadelphia — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Philadelphia%2C%20PA', 'Philadelphia', 'PA', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Atlanta — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Atlanta%2C%20GA', 'Atlanta', 'GA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Atlanta — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Atlanta%2C%20GA', 'Atlanta', 'GA', true, 'Indeed job board search'),
('band', 'other', 'Indeed Atlanta — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Atlanta%2C%20GA', 'Atlanta', 'GA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Atlanta — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Atlanta%2C%20GA', 'Atlanta', 'GA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Atlanta — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Atlanta%2C%20GA', 'Atlanta', 'GA', true, 'Indeed job board search'),
('any', 'other', 'Indeed Atlanta — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Atlanta%2C%20GA', 'Atlanta', 'GA', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Boston — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Boston%2C%20MA', 'Boston', 'MA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Boston — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Boston%2C%20MA', 'Boston', 'MA', true, 'Indeed job board search'),
('band', 'other', 'Indeed Boston — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Boston%2C%20MA', 'Boston', 'MA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Boston — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Boston%2C%20MA', 'Boston', 'MA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Boston — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Boston%2C%20MA', 'Boston', 'MA', true, 'Indeed job board search'),
('any', 'other', 'Indeed Boston — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Boston%2C%20MA', 'Boston', 'MA', true, 'Indeed job board search'),
('musician', 'other', 'Indeed San Francisco — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=San%20Francisco%2C%20CA', 'San Francisco', 'CA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed San Francisco — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=San%20Francisco%2C%20CA', 'San Francisco', 'CA', true, 'Indeed job board search'),
('band', 'other', 'Indeed San Francisco — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=San%20Francisco%2C%20CA', 'San Francisco', 'CA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed San Francisco — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=San%20Francisco%2C%20CA', 'San Francisco', 'CA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed San Francisco — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=San%20Francisco%2C%20CA', 'San Francisco', 'CA', true, 'Indeed job board search'),
('any', 'other', 'Indeed San Francisco — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=San%20Francisco%2C%20CA', 'San Francisco', 'CA', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Phoenix — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Phoenix%2C%20AZ', 'Phoenix', 'AZ', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Phoenix — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Phoenix%2C%20AZ', 'Phoenix', 'AZ', true, 'Indeed job board search'),
('band', 'other', 'Indeed Phoenix — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Phoenix%2C%20AZ', 'Phoenix', 'AZ', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Phoenix — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Phoenix%2C%20AZ', 'Phoenix', 'AZ', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Phoenix — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Phoenix%2C%20AZ', 'Phoenix', 'AZ', true, 'Indeed job board search'),
('any', 'other', 'Indeed Phoenix — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Phoenix%2C%20AZ', 'Phoenix', 'AZ', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Detroit — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Detroit%2C%20MI', 'Detroit', 'MI', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Detroit — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Detroit%2C%20MI', 'Detroit', 'MI', true, 'Indeed job board search'),
('band', 'other', 'Indeed Detroit — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Detroit%2C%20MI', 'Detroit', 'MI', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Detroit — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Detroit%2C%20MI', 'Detroit', 'MI', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Detroit — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Detroit%2C%20MI', 'Detroit', 'MI', true, 'Indeed job board search'),
('any', 'other', 'Indeed Detroit — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Detroit%2C%20MI', 'Detroit', 'MI', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Seattle — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Seattle%2C%20WA', 'Seattle', 'WA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Seattle — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Seattle%2C%20WA', 'Seattle', 'WA', true, 'Indeed job board search'),
('band', 'other', 'Indeed Seattle — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Seattle%2C%20WA', 'Seattle', 'WA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Seattle — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Seattle%2C%20WA', 'Seattle', 'WA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Seattle — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Seattle%2C%20WA', 'Seattle', 'WA', true, 'Indeed job board search'),
('any', 'other', 'Indeed Seattle — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Seattle%2C%20WA', 'Seattle', 'WA', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Minneapolis — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Minneapolis%2C%20MN', 'Minneapolis', 'MN', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Minneapolis — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Minneapolis%2C%20MN', 'Minneapolis', 'MN', true, 'Indeed job board search'),
('band', 'other', 'Indeed Minneapolis — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Minneapolis%2C%20MN', 'Minneapolis', 'MN', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Minneapolis — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Minneapolis%2C%20MN', 'Minneapolis', 'MN', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Minneapolis — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Minneapolis%2C%20MN', 'Minneapolis', 'MN', true, 'Indeed job board search'),
('any', 'other', 'Indeed Minneapolis — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Minneapolis%2C%20MN', 'Minneapolis', 'MN', true, 'Indeed job board search'),
('musician', 'other', 'Indeed San Diego — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=San%20Diego%2C%20CA', 'San Diego', 'CA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed San Diego — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=San%20Diego%2C%20CA', 'San Diego', 'CA', true, 'Indeed job board search'),
('band', 'other', 'Indeed San Diego — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=San%20Diego%2C%20CA', 'San Diego', 'CA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed San Diego — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=San%20Diego%2C%20CA', 'San Diego', 'CA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed San Diego — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=San%20Diego%2C%20CA', 'San Diego', 'CA', true, 'Indeed job board search'),
('any', 'other', 'Indeed San Diego — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=San%20Diego%2C%20CA', 'San Diego', 'CA', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Tampa — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Tampa%2C%20FL', 'Tampa', 'FL', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Tampa — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Tampa%2C%20FL', 'Tampa', 'FL', true, 'Indeed job board search'),
('band', 'other', 'Indeed Tampa — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Tampa%2C%20FL', 'Tampa', 'FL', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Tampa — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Tampa%2C%20FL', 'Tampa', 'FL', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Tampa — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Tampa%2C%20FL', 'Tampa', 'FL', true, 'Indeed job board search'),
('any', 'other', 'Indeed Tampa — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Tampa%2C%20FL', 'Tampa', 'FL', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Denver — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Denver%2C%20CO', 'Denver', 'CO', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Denver — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Denver%2C%20CO', 'Denver', 'CO', true, 'Indeed job board search'),
('band', 'other', 'Indeed Denver — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Denver%2C%20CO', 'Denver', 'CO', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Denver — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Denver%2C%20CO', 'Denver', 'CO', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Denver — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Denver%2C%20CO', 'Denver', 'CO', true, 'Indeed job board search'),
('any', 'other', 'Indeed Denver — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Denver%2C%20CO', 'Denver', 'CO', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Baltimore — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Baltimore%2C%20MD', 'Baltimore', 'MD', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Baltimore — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Baltimore%2C%20MD', 'Baltimore', 'MD', true, 'Indeed job board search'),
('band', 'other', 'Indeed Baltimore — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Baltimore%2C%20MD', 'Baltimore', 'MD', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Baltimore — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Baltimore%2C%20MD', 'Baltimore', 'MD', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Baltimore — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Baltimore%2C%20MD', 'Baltimore', 'MD', true, 'Indeed job board search'),
('any', 'other', 'Indeed Baltimore — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Baltimore%2C%20MD', 'Baltimore', 'MD', true, 'Indeed job board search'),
('musician', 'other', 'Indeed St. Louis — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=St.%20Louis%2C%20MO', 'St. Louis', 'MO', true, 'Indeed job board search'),
('dj', 'other', 'Indeed St. Louis — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=St.%20Louis%2C%20MO', 'St. Louis', 'MO', true, 'Indeed job board search'),
('band', 'other', 'Indeed St. Louis — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=St.%20Louis%2C%20MO', 'St. Louis', 'MO', true, 'Indeed job board search'),
('singer', 'other', 'Indeed St. Louis — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=St.%20Louis%2C%20MO', 'St. Louis', 'MO', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed St. Louis — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=St.%20Louis%2C%20MO', 'St. Louis', 'MO', true, 'Indeed job board search'),
('any', 'other', 'Indeed St. Louis — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=St.%20Louis%2C%20MO', 'St. Louis', 'MO', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Orlando — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Orlando%2C%20FL', 'Orlando', 'FL', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Orlando — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Orlando%2C%20FL', 'Orlando', 'FL', true, 'Indeed job board search'),
('band', 'other', 'Indeed Orlando — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Orlando%2C%20FL', 'Orlando', 'FL', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Orlando — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Orlando%2C%20FL', 'Orlando', 'FL', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Orlando — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Orlando%2C%20FL', 'Orlando', 'FL', true, 'Indeed job board search'),
('any', 'other', 'Indeed Orlando — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Orlando%2C%20FL', 'Orlando', 'FL', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Portland — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Portland%2C%20OR', 'Portland', 'OR', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Portland — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Portland%2C%20OR', 'Portland', 'OR', true, 'Indeed job board search'),
('band', 'other', 'Indeed Portland — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Portland%2C%20OR', 'Portland', 'OR', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Portland — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Portland%2C%20OR', 'Portland', 'OR', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Portland — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Portland%2C%20OR', 'Portland', 'OR', true, 'Indeed job board search'),
('any', 'other', 'Indeed Portland — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Portland%2C%20OR', 'Portland', 'OR', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Charlotte — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Charlotte%2C%20NC', 'Charlotte', 'NC', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Charlotte — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Charlotte%2C%20NC', 'Charlotte', 'NC', true, 'Indeed job board search'),
('band', 'other', 'Indeed Charlotte — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Charlotte%2C%20NC', 'Charlotte', 'NC', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Charlotte — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Charlotte%2C%20NC', 'Charlotte', 'NC', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Charlotte — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Charlotte%2C%20NC', 'Charlotte', 'NC', true, 'Indeed job board search'),
('any', 'other', 'Indeed Charlotte — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Charlotte%2C%20NC', 'Charlotte', 'NC', true, 'Indeed job board search'),
('musician', 'other', 'Indeed San Antonio — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=San%20Antonio%2C%20TX', 'San Antonio', 'TX', true, 'Indeed job board search'),
('dj', 'other', 'Indeed San Antonio — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=San%20Antonio%2C%20TX', 'San Antonio', 'TX', true, 'Indeed job board search'),
('band', 'other', 'Indeed San Antonio — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=San%20Antonio%2C%20TX', 'San Antonio', 'TX', true, 'Indeed job board search'),
('singer', 'other', 'Indeed San Antonio — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=San%20Antonio%2C%20TX', 'San Antonio', 'TX', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed San Antonio — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=San%20Antonio%2C%20TX', 'San Antonio', 'TX', true, 'Indeed job board search'),
('any', 'other', 'Indeed San Antonio — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=San%20Antonio%2C%20TX', 'San Antonio', 'TX', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Austin — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Austin%2C%20TX', 'Austin', 'TX', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Austin — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Austin%2C%20TX', 'Austin', 'TX', true, 'Indeed job board search'),
('band', 'other', 'Indeed Austin — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Austin%2C%20TX', 'Austin', 'TX', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Austin — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Austin%2C%20TX', 'Austin', 'TX', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Austin — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Austin%2C%20TX', 'Austin', 'TX', true, 'Indeed job board search'),
('any', 'other', 'Indeed Austin — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Austin%2C%20TX', 'Austin', 'TX', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Sacramento — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Sacramento%2C%20CA', 'Sacramento', 'CA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Sacramento — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Sacramento%2C%20CA', 'Sacramento', 'CA', true, 'Indeed job board search'),
('band', 'other', 'Indeed Sacramento — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Sacramento%2C%20CA', 'Sacramento', 'CA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Sacramento — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Sacramento%2C%20CA', 'Sacramento', 'CA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Sacramento — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Sacramento%2C%20CA', 'Sacramento', 'CA', true, 'Indeed job board search'),
('any', 'other', 'Indeed Sacramento — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Sacramento%2C%20CA', 'Sacramento', 'CA', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Pittsburgh — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Pittsburgh%2C%20PA', 'Pittsburgh', 'PA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Pittsburgh — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Pittsburgh%2C%20PA', 'Pittsburgh', 'PA', true, 'Indeed job board search'),
('band', 'other', 'Indeed Pittsburgh — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Pittsburgh%2C%20PA', 'Pittsburgh', 'PA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Pittsburgh — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Pittsburgh%2C%20PA', 'Pittsburgh', 'PA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Pittsburgh — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Pittsburgh%2C%20PA', 'Pittsburgh', 'PA', true, 'Indeed job board search'),
('any', 'other', 'Indeed Pittsburgh — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Pittsburgh%2C%20PA', 'Pittsburgh', 'PA', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Cincinnati — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Cincinnati%2C%20OH', 'Cincinnati', 'OH', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Cincinnati — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Cincinnati%2C%20OH', 'Cincinnati', 'OH', true, 'Indeed job board search'),
('band', 'other', 'Indeed Cincinnati — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Cincinnati%2C%20OH', 'Cincinnati', 'OH', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Cincinnati — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Cincinnati%2C%20OH', 'Cincinnati', 'OH', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Cincinnati — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Cincinnati%2C%20OH', 'Cincinnati', 'OH', true, 'Indeed job board search'),
('any', 'other', 'Indeed Cincinnati — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Cincinnati%2C%20OH', 'Cincinnati', 'OH', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Las Vegas — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Las%20Vegas%2C%20NV', 'Las Vegas', 'NV', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Las Vegas — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Las%20Vegas%2C%20NV', 'Las Vegas', 'NV', true, 'Indeed job board search'),
('band', 'other', 'Indeed Las Vegas — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Las%20Vegas%2C%20NV', 'Las Vegas', 'NV', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Las Vegas — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Las%20Vegas%2C%20NV', 'Las Vegas', 'NV', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Las Vegas — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Las%20Vegas%2C%20NV', 'Las Vegas', 'NV', true, 'Indeed job board search'),
('any', 'other', 'Indeed Las Vegas — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Las%20Vegas%2C%20NV', 'Las Vegas', 'NV', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Kansas City — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Kansas%20City%2C%20MO', 'Kansas City', 'MO', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Kansas City — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Kansas%20City%2C%20MO', 'Kansas City', 'MO', true, 'Indeed job board search'),
('band', 'other', 'Indeed Kansas City — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Kansas%20City%2C%20MO', 'Kansas City', 'MO', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Kansas City — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Kansas%20City%2C%20MO', 'Kansas City', 'MO', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Kansas City — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Kansas%20City%2C%20MO', 'Kansas City', 'MO', true, 'Indeed job board search'),
('any', 'other', 'Indeed Kansas City — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Kansas%20City%2C%20MO', 'Kansas City', 'MO', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Cleveland — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Cleveland%2C%20OH', 'Cleveland', 'OH', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Cleveland — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Cleveland%2C%20OH', 'Cleveland', 'OH', true, 'Indeed job board search'),
('band', 'other', 'Indeed Cleveland — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Cleveland%2C%20OH', 'Cleveland', 'OH', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Cleveland — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Cleveland%2C%20OH', 'Cleveland', 'OH', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Cleveland — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Cleveland%2C%20OH', 'Cleveland', 'OH', true, 'Indeed job board search'),
('any', 'other', 'Indeed Cleveland — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Cleveland%2C%20OH', 'Cleveland', 'OH', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Columbus — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Columbus%2C%20OH', 'Columbus', 'OH', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Columbus — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Columbus%2C%20OH', 'Columbus', 'OH', true, 'Indeed job board search'),
('band', 'other', 'Indeed Columbus — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Columbus%2C%20OH', 'Columbus', 'OH', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Columbus — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Columbus%2C%20OH', 'Columbus', 'OH', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Columbus — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Columbus%2C%20OH', 'Columbus', 'OH', true, 'Indeed job board search'),
('any', 'other', 'Indeed Columbus — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Columbus%2C%20OH', 'Columbus', 'OH', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Indianapolis — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Indianapolis%2C%20IN', 'Indianapolis', 'IN', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Indianapolis — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Indianapolis%2C%20IN', 'Indianapolis', 'IN', true, 'Indeed job board search'),
('band', 'other', 'Indeed Indianapolis — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Indianapolis%2C%20IN', 'Indianapolis', 'IN', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Indianapolis — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Indianapolis%2C%20IN', 'Indianapolis', 'IN', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Indianapolis — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Indianapolis%2C%20IN', 'Indianapolis', 'IN', true, 'Indeed job board search'),
('any', 'other', 'Indeed Indianapolis — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Indianapolis%2C%20IN', 'Indianapolis', 'IN', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Nashville — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Nashville%2C%20TN', 'Nashville', 'TN', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Nashville — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Nashville%2C%20TN', 'Nashville', 'TN', true, 'Indeed job board search'),
('band', 'other', 'Indeed Nashville — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Nashville%2C%20TN', 'Nashville', 'TN', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Nashville — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Nashville%2C%20TN', 'Nashville', 'TN', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Nashville — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Nashville%2C%20TN', 'Nashville', 'TN', true, 'Indeed job board search'),
('any', 'other', 'Indeed Nashville — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Nashville%2C%20TN', 'Nashville', 'TN', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Milwaukee — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Milwaukee%2C%20WI', 'Milwaukee', 'WI', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Milwaukee — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Milwaukee%2C%20WI', 'Milwaukee', 'WI', true, 'Indeed job board search'),
('band', 'other', 'Indeed Milwaukee — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Milwaukee%2C%20WI', 'Milwaukee', 'WI', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Milwaukee — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Milwaukee%2C%20WI', 'Milwaukee', 'WI', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Milwaukee — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Milwaukee%2C%20WI', 'Milwaukee', 'WI', true, 'Indeed job board search'),
('any', 'other', 'Indeed Milwaukee — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Milwaukee%2C%20WI', 'Milwaukee', 'WI', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Raleigh — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Raleigh%2C%20NC', 'Raleigh', 'NC', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Raleigh — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Raleigh%2C%20NC', 'Raleigh', 'NC', true, 'Indeed job board search'),
('band', 'other', 'Indeed Raleigh — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Raleigh%2C%20NC', 'Raleigh', 'NC', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Raleigh — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Raleigh%2C%20NC', 'Raleigh', 'NC', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Raleigh — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Raleigh%2C%20NC', 'Raleigh', 'NC', true, 'Indeed job board search'),
('any', 'other', 'Indeed Raleigh — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Raleigh%2C%20NC', 'Raleigh', 'NC', true, 'Indeed job board search'),
('musician', 'other', 'Indeed New Orleans — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=New%20Orleans%2C%20LA', 'New Orleans', 'LA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed New Orleans — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=New%20Orleans%2C%20LA', 'New Orleans', 'LA', true, 'Indeed job board search'),
('band', 'other', 'Indeed New Orleans — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=New%20Orleans%2C%20LA', 'New Orleans', 'LA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed New Orleans — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=New%20Orleans%2C%20LA', 'New Orleans', 'LA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed New Orleans — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=New%20Orleans%2C%20LA', 'New Orleans', 'LA', true, 'Indeed job board search'),
('any', 'other', 'Indeed New Orleans — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=New%20Orleans%2C%20LA', 'New Orleans', 'LA', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Memphis — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Memphis%2C%20TN', 'Memphis', 'TN', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Memphis — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Memphis%2C%20TN', 'Memphis', 'TN', true, 'Indeed job board search'),
('band', 'other', 'Indeed Memphis — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Memphis%2C%20TN', 'Memphis', 'TN', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Memphis — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Memphis%2C%20TN', 'Memphis', 'TN', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Memphis — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Memphis%2C%20TN', 'Memphis', 'TN', true, 'Indeed job board search'),
('any', 'other', 'Indeed Memphis — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Memphis%2C%20TN', 'Memphis', 'TN', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Louisville — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Louisville%2C%20KY', 'Louisville', 'KY', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Louisville — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Louisville%2C%20KY', 'Louisville', 'KY', true, 'Indeed job board search'),
('band', 'other', 'Indeed Louisville — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Louisville%2C%20KY', 'Louisville', 'KY', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Louisville — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Louisville%2C%20KY', 'Louisville', 'KY', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Louisville — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Louisville%2C%20KY', 'Louisville', 'KY', true, 'Indeed job board search'),
('any', 'other', 'Indeed Louisville — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Louisville%2C%20KY', 'Louisville', 'KY', true, 'Indeed job board search'),
('musician', 'other', 'Indeed Richmond — musician wanted', 'https://www.indeed.com/jobs?q=musician%20wanted&l=Richmond%2C%20VA', 'Richmond', 'VA', true, 'Indeed job board search'),
('dj', 'other', 'Indeed Richmond — DJ wanted', 'https://www.indeed.com/jobs?q=DJ%20wanted&l=Richmond%2C%20VA', 'Richmond', 'VA', true, 'Indeed job board search'),
('band', 'other', 'Indeed Richmond — band wanted', 'https://www.indeed.com/jobs?q=band%20wanted&l=Richmond%2C%20VA', 'Richmond', 'VA', true, 'Indeed job board search'),
('singer', 'other', 'Indeed Richmond — singer wanted', 'https://www.indeed.com/jobs?q=singer%20wanted&l=Richmond%2C%20VA', 'Richmond', 'VA', true, 'Indeed job board search'),
('rapper', 'other', 'Indeed Richmond — rapper wanted', 'https://www.indeed.com/jobs?q=rapper%20wanted&l=Richmond%2C%20VA', 'Richmond', 'VA', true, 'Indeed job board search'),
('any', 'other', 'Indeed Richmond — performer wanted', 'https://www.indeed.com/jobs?q=performer%20wanted&l=Richmond%2C%20VA', 'Richmond', 'VA', true, 'Indeed job board search'),
('any', 'other', 'Reddit r/nyc — gigs search', 'https://www.reddit.com/r/nyc/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'New York', 'NY', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/LosAngeles — gigs search', 'https://www.reddit.com/r/LosAngeles/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Los Angeles', 'CA', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/chicago — gigs search', 'https://www.reddit.com/r/chicago/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Chicago', 'IL', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Dallas — gigs search', 'https://www.reddit.com/r/Dallas/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Dallas', 'TX', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/houston — gigs search', 'https://www.reddit.com/r/houston/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Houston', 'TX', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/washingtondc — gigs search', 'https://www.reddit.com/r/washingtondc/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Washington DC', NULL, true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Miami — gigs search', 'https://www.reddit.com/r/Miami/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Miami', 'FL', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/philadelphia — gigs search', 'https://www.reddit.com/r/philadelphia/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Philadelphia', 'PA', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Atlanta — gigs search', 'https://www.reddit.com/r/Atlanta/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Atlanta', 'GA', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/boston — gigs search', 'https://www.reddit.com/r/boston/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Boston', 'MA', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/sanfrancisco — gigs search', 'https://www.reddit.com/r/sanfrancisco/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'San Francisco', 'CA', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/phoenix — gigs search', 'https://www.reddit.com/r/phoenix/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Phoenix', 'AZ', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Detroit — gigs search', 'https://www.reddit.com/r/Detroit/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Detroit', 'MI', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Seattle — gigs search', 'https://www.reddit.com/r/Seattle/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Seattle', 'WA', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/minnesota — gigs search', 'https://www.reddit.com/r/minnesota/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Minneapolis', 'MN', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/sandiego — gigs search', 'https://www.reddit.com/r/sandiego/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'San Diego', 'CA', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/tampa — gigs search', 'https://www.reddit.com/r/tampa/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Tampa', 'FL', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Denver — gigs search', 'https://www.reddit.com/r/Denver/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Denver', 'CO', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/baltimore — gigs search', 'https://www.reddit.com/r/baltimore/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Baltimore', 'MD', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/StLouis — gigs search', 'https://www.reddit.com/r/StLouis/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'St. Louis', 'MO', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/orlando — gigs search', 'https://www.reddit.com/r/orlando/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Orlando', 'FL', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Portland — gigs search', 'https://www.reddit.com/r/Portland/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Portland', 'OR', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Charlotte — gigs search', 'https://www.reddit.com/r/Charlotte/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Charlotte', 'NC', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/sanantonio — gigs search', 'https://www.reddit.com/r/sanantonio/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'San Antonio', 'TX', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Austin — gigs search', 'https://www.reddit.com/r/Austin/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Austin', 'TX', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Sacramento — gigs search', 'https://www.reddit.com/r/Sacramento/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Sacramento', 'CA', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/pittsburgh — gigs search', 'https://www.reddit.com/r/pittsburgh/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Pittsburgh', 'PA', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/cincinnati — gigs search', 'https://www.reddit.com/r/cincinnati/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Cincinnati', 'OH', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/vegas — gigs search', 'https://www.reddit.com/r/vegas/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Las Vegas', 'NV', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/kansascity — gigs search', 'https://www.reddit.com/r/kansascity/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Kansas City', 'MO', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Cleveland — gigs search', 'https://www.reddit.com/r/Cleveland/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Cleveland', 'OH', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Columbus — gigs search', 'https://www.reddit.com/r/Columbus/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Columbus', 'OH', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/indianapolis — gigs search', 'https://www.reddit.com/r/indianapolis/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Indianapolis', 'IN', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/nashville — gigs search', 'https://www.reddit.com/r/nashville/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Nashville', 'TN', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/milwaukee — gigs search', 'https://www.reddit.com/r/milwaukee/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Milwaukee', 'WI', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/raleigh — gigs search', 'https://www.reddit.com/r/raleigh/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Raleigh', 'NC', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/NewOrleans — gigs search', 'https://www.reddit.com/r/NewOrleans/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'New Orleans', 'LA', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/memphis — gigs search', 'https://www.reddit.com/r/memphis/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Memphis', 'TN', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/Louisville — gigs search', 'https://www.reddit.com/r/Louisville/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Louisville', 'KY', true, 'Reddit JSON feed'),
('any', 'other', 'Reddit r/rva — gigs search', 'https://www.reddit.com/r/rva/search.json?q=musician%20OR%20DJ%20OR%20band%20OR%20singer%20OR%20rapper%20OR%20poet%20wanted%20OR%20needed&restrict_sr=on&sort=new&t=month', 'Richmond', 'VA', true, 'Reddit JSON feed'),
('musician', 'other', 'Backstage — Musicians casting calls', 'https://www.backstage.com/casting/musicians/', NULL, NULL, true, 'Backstage casting calls'),
('singer', 'other', 'Backstage — Singers casting calls', 'https://www.backstage.com/casting/singers/', NULL, NULL, true, 'Backstage casting calls'),
('any', 'other', 'Backstage — Performers casting calls', 'https://www.backstage.com/casting/performers/', NULL, NULL, true, 'Backstage casting calls'),
('poet', 'calendar', 'Poets.org events', 'https://poets.org/events', NULL, NULL, true, 'Poetry/spoken-word aggregator'),
('poet', 'calendar', 'Poetry Foundation events', 'https://www.poetryfoundation.org/events', NULL, NULL, true, 'Poetry/spoken-word aggregator'),
('poet', 'calendar', 'Nuyorican Poets Cafe (NYC)', 'https://www.nuyorican.org/poetry/', NULL, NULL, true, 'Poetry/spoken-word aggregator'),
('poet', 'calendar', 'Urban Word NYC programs', 'https://urbanwordnyc.org/programs/', NULL, NULL, true, 'Poetry/spoken-word aggregator'),
('poet', 'calendar', 'Poetry Slam Inc. calendar', 'https://www.poetryslam.com/calendar/', NULL, NULL, true, 'Poetry/spoken-word aggregator'),
('any', 'other', 'FestivalNet — Seeking bands & musicians', 'https://festivalnet.com/festivals/seeking/Bands-Musicians', NULL, NULL, true, 'Festival aggregator'),
('any', 'other', 'FestivalNet — Seeking performers', 'https://festivalnet.com/festivals/seeking/Performers', NULL, NULL, true, 'Festival aggregator')
ON CONFLICT (url) DO NOTHING;

-- =============================================================================
-- END seed (450 sources)
-- =============================================================================
